export const listBooking = [
    {
        code: '07K64R',
        pickStation: {
            id: 10,
            arrivalTime: 0,
            stationType: 'pick',
            station: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
        },
        dropStation: {
            id: 9,
            arrivalTime: 0,
            stationType: 'drop',
            station: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
        },
        bookingDate: '2023-11-13T15:36:23.017881',
        ticketNumber: 1,
        name: 'Lê Thị Kim Lệ',
        email: '20110248@student.hcmute.edu.vn',
        tel: '09090909091',
        status: 'Thành công',
        bookingUser: {
            id: 6,
            name: 'Lê Thị Kim Lệ Kim',
            email: '20110248@student.hcmute.edu.vn',
            tel: '09090909091',
            gender: 'false',
            account: {
                id: 8,
                username: '09090909091',
                roleName: 'CUSTOMER',
                active: true,
            },
            customer: {
                customerId: 5,
                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
            },
        },
        conductStaff: null,
        transaction: {
            id: 13,
            transactionType: 'Thanh toán',
            amount: 275000,
            paymentTime: '2023-11-13T15:39:27.203279',
            referenceId: 'FDZ0Z918YR',
            paymentMethod: 'Momo',
        },
        tickets: [
            {
                id: 91,
                seat: 'A8',
                state: 'Đã hủy',
                checkedIn: false,
                histories: [
                    {
                        id: 5,
                        action: 'Đổi',
                        timestamp: '2023-11-15T21:39:20.231654',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 8,
                            action: 'Đổi',
                            timeRequired: 24,
                            numberRequired: 30,
                            minNumberRequired: 1,
                            refundRate: 0,
                            description:
                                'Khách hàng được hỗ trợ đổi vé một lần duy nhất nếu yêu cầu đổi vé trước ít nhất 24 tiếng trước giờ khởi hành',
                        },
                        transaction: null,
                    },
                    {
                        id: 13,
                        action: 'Đổi',
                        timestamp: '2023-11-16T21:53:35.716253',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 2,
                            action: 'Hủy',
                            timeRequired: 4,
                            numberRequired: 3,
                            minNumberRequired: 1,
                            refundRate: 0.9,
                            description:
                                'Khách hàng hủy từ 1-3 vé trước ít nhất 4 tiếng trước giờ khởi hành sẽ được hoàn 90% tiền vé đối với vé thường',
                        },
                        transaction: {
                            id: 15,
                            transactionType: 'Hoàn tiền',
                            amount: 247500,
                            paymentTime: '2023-11-16T21:53:35.712059',
                            referenceId: 'Z4UIJS0MZU',
                            paymentMethod: 'Momo',
                        },
                    },
                ],
                schedule: {
                    id: 20,
                    departDate: '2023-12-12',
                    departTime: '07:00:00',
                    ticketPrice: 275000,
                    finishTime: '00:00:00',
                    availability: 9,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
        ],
        trip: {
            id: 4,
            turn: false,
            startStation: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
            endStation: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
            route: {
                id: 2,
                distance: 75,
                departure: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                destination: {
                    id: 3,
                    name: 'Bến Tre',
                },
                price: 130000,
                schedule: 'QL1A -> Tân An -> Mỹ Tho -> Bến Tre -> Trà Vinh',
                parents: 1,
                hours: 2,
                busType: {
                    id: 2,
                    name: 'bumk_bus',
                    capacity: 33,
                    fee: 20000,
                    description: 'Xe giường nằm 43 chỗ',
                    seatMap: {
                        id: 2,
                        rowNo: 7,
                        colNo: 5,
                        floorNo: 2,
                        seats: [
                            {
                                id: 29,
                                name: 'A01',
                                row: 0,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 30,
                                name: 'A02',
                                row: 0,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 31,
                                name: 'A03',
                                row: 0,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 32,
                                name: 'A04',
                                row: 1,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 33,
                                name: 'A05',
                                row: 1,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 34,
                                name: 'A06',
                                row: 1,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 35,
                                name: 'A07',
                                row: 2,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 36,
                                name: 'A08',
                                row: 2,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 37,
                                name: 'A09',
                                row: 2,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 38,
                                name: 'A10',
                                row: 3,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 39,
                                name: 'A11',
                                row: 3,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 40,
                                name: 'A12',
                                row: 3,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 41,
                                name: 'A13',
                                row: 4,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 42,
                                name: 'A14',
                                row: 4,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 43,
                                name: 'A15',
                                row: 4,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 44,
                                name: 'A16',
                                row: 5,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 45,
                                name: 'A17',
                                row: 5,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 46,
                                name: 'A18',
                                row: 6,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 47,
                                name: 'A19',
                                row: 6,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 48,
                                name: 'A20',
                                row: 6,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 49,
                                name: 'A21',
                                row: 6,
                                col: 3,
                                floor: 1,
                            },
                            {
                                id: 50,
                                name: 'A22',
                                row: 6,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 51,
                                name: 'B01',
                                row: 0,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 52,
                                name: 'B02',
                                row: 0,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 53,
                                name: 'B03',
                                row: 0,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 54,
                                name: 'B04',
                                row: 1,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 55,
                                name: 'B05',
                                row: 1,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 56,
                                name: 'B06',
                                row: 1,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 57,
                                name: 'B07',
                                row: 2,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 58,
                                name: 'B08',
                                row: 2,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 59,
                                name: 'B09',
                                row: 2,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 60,
                                name: 'B10',
                                row: 3,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 61,
                                name: 'B11',
                                row: 3,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 62,
                                name: 'B12',
                                row: 3,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 63,
                                name: 'B13',
                                row: 4,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 64,
                                name: 'B14',
                                row: 4,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 65,
                                name: 'B15',
                                row: 4,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 66,
                                name: 'B17',
                                row: 5,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 67,
                                name: 'B18',
                                row: 6,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 68,
                                name: 'B19',
                                row: 6,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 69,
                                name: 'B20',
                                row: 6,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 70,
                                name: 'B21',
                                row: 6,
                                col: 3,
                                floor: 2,
                            },
                            {
                                id: 71,
                                name: 'B22',
                                row: 6,
                                col: 4,
                                floor: 2,
                            },
                        ],
                    },
                },
            },
        },
        ticketing: false,
    },
    {
        code: '07K64U',
        pickStation: {
            id: 10,
            arrivalTime: 0,
            stationType: 'pick',
            station: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
        },
        dropStation: {
            id: 9,
            arrivalTime: 0,
            stationType: 'drop',
            station: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
        },
        bookingDate: '2023-11-13T15:36:23.017881',
        ticketNumber: 1,
        name: 'Lê Thị Kim Lệ',
        email: '20110248@student.hcmute.edu.vn',
        tel: '09090909091',
        status: 'Thành công',
        bookingUser: {
            id: 6,
            name: 'Lê Thị Kim Lệ Kim',
            email: '20110248@student.hcmute.edu.vn',
            tel: '09090909091',
            gender: 'false',
            account: {
                id: 8,
                username: '09090909091',
                roleName: 'CUSTOMER',
                active: true,
            },
            customer: {
                customerId: 5,
                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
            },
        },
        conductStaff: null,
        transaction: {
            id: 13,
            transactionType: 'Thanh toán',
            amount: 275000,
            paymentTime: '2023-11-13T15:39:27.203279',
            referenceId: 'FDZ0Z918YR',
            paymentMethod: 'Momo',
        },
        tickets: [
            {
                id: 91,
                seat: 'A8',
                state: 'Đã hủy',
                checkedIn: false,
                histories: [
                    {
                        id: 5,
                        action: 'Đổi',
                        timestamp: '2023-11-15T21:39:20.231654',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 8,
                            action: 'Đổi',
                            timeRequired: 24,
                            numberRequired: 30,
                            minNumberRequired: 1,
                            refundRate: 0,
                            description:
                                'Khách hàng được hỗ trợ đổi vé một lần duy nhất nếu yêu cầu đổi vé trước ít nhất 24 tiếng trước giờ khởi hành',
                        },
                        transaction: null,
                    },
                    {
                        id: 13,
                        action: 'Đổi',
                        timestamp: '2023-11-16T21:53:35.716253',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 2,
                            action: 'Hủy',
                            timeRequired: 4,
                            numberRequired: 3,
                            minNumberRequired: 1,
                            refundRate: 0.9,
                            description:
                                'Khách hàng hủy từ 1-3 vé trước ít nhất 4 tiếng trước giờ khởi hành sẽ được hoàn 90% tiền vé đối với vé thường',
                        },
                        transaction: {
                            id: 15,
                            transactionType: 'Hoàn tiền',
                            amount: 247500,
                            paymentTime: '2023-11-16T21:53:35.712059',
                            referenceId: 'Z4UIJS0MZU',
                            paymentMethod: 'Momo',
                        },
                    },
                ],
                schedule: {
                    id: 20,
                    departDate: '2023-12-12',
                    departTime: '07:00:00',
                    ticketPrice: 275000,
                    finishTime: '00:00:00',
                    availability: 9,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
        ],
        trip: {
            id: 4,
            turn: false,
            startStation: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
            endStation: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
            route: {
                id: 2,
                distance: 75,
                departure: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                destination: {
                    id: 3,
                    name: 'Bến Tre',
                },
                price: 130000,
                schedule: 'QL1A -> Tân An -> Mỹ Tho -> Bến Tre -> Trà Vinh',
                parents: 1,
                hours: 2,
                busType: {
                    id: 2,
                    name: 'bumk_bus',
                    capacity: 33,
                    fee: 20000,
                    description: 'Xe giường nằm 43 chỗ',
                    seatMap: {
                        id: 2,
                        rowNo: 7,
                        colNo: 5,
                        floorNo: 2,
                        seats: [
                            {
                                id: 29,
                                name: 'A01',
                                row: 0,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 30,
                                name: 'A02',
                                row: 0,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 31,
                                name: 'A03',
                                row: 0,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 32,
                                name: 'A04',
                                row: 1,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 33,
                                name: 'A05',
                                row: 1,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 34,
                                name: 'A06',
                                row: 1,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 35,
                                name: 'A07',
                                row: 2,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 36,
                                name: 'A08',
                                row: 2,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 37,
                                name: 'A09',
                                row: 2,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 38,
                                name: 'A10',
                                row: 3,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 39,
                                name: 'A11',
                                row: 3,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 40,
                                name: 'A12',
                                row: 3,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 41,
                                name: 'A13',
                                row: 4,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 42,
                                name: 'A14',
                                row: 4,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 43,
                                name: 'A15',
                                row: 4,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 44,
                                name: 'A16',
                                row: 5,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 45,
                                name: 'A17',
                                row: 5,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 46,
                                name: 'A18',
                                row: 6,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 47,
                                name: 'A19',
                                row: 6,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 48,
                                name: 'A20',
                                row: 6,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 49,
                                name: 'A21',
                                row: 6,
                                col: 3,
                                floor: 1,
                            },
                            {
                                id: 50,
                                name: 'A22',
                                row: 6,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 51,
                                name: 'B01',
                                row: 0,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 52,
                                name: 'B02',
                                row: 0,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 53,
                                name: 'B03',
                                row: 0,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 54,
                                name: 'B04',
                                row: 1,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 55,
                                name: 'B05',
                                row: 1,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 56,
                                name: 'B06',
                                row: 1,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 57,
                                name: 'B07',
                                row: 2,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 58,
                                name: 'B08',
                                row: 2,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 59,
                                name: 'B09',
                                row: 2,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 60,
                                name: 'B10',
                                row: 3,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 61,
                                name: 'B11',
                                row: 3,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 62,
                                name: 'B12',
                                row: 3,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 63,
                                name: 'B13',
                                row: 4,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 64,
                                name: 'B14',
                                row: 4,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 65,
                                name: 'B15',
                                row: 4,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 66,
                                name: 'B17',
                                row: 5,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 67,
                                name: 'B18',
                                row: 6,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 68,
                                name: 'B19',
                                row: 6,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 69,
                                name: 'B20',
                                row: 6,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 70,
                                name: 'B21',
                                row: 6,
                                col: 3,
                                floor: 2,
                            },
                            {
                                id: 71,
                                name: 'B22',
                                row: 6,
                                col: 4,
                                floor: 2,
                            },
                        ],
                    },
                },
            },
        },
        ticketing: false,
    },
    {
        code: '07K64E',
        pickStation: {
            id: 10,
            arrivalTime: 0,
            stationType: 'pick',
            station: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
        },
        dropStation: {
            id: 9,
            arrivalTime: 0,
            stationType: 'drop',
            station: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
        },
        bookingDate: '2023-11-13T15:36:23.017881',
        ticketNumber: 1,
        name: 'Lê Thị Kim Lệ',
        email: '20110248@student.hcmute.edu.vn',
        tel: '09090909091',
        status: 'Thành công',
        bookingUser: {
            id: 6,
            name: 'Lê Thị Kim Lệ Kim',
            email: '20110248@student.hcmute.edu.vn',
            tel: '09090909091',
            gender: 'false',
            account: {
                id: 8,
                username: '09090909091',
                roleName: 'CUSTOMER',
                active: true,
            },
            customer: {
                customerId: 5,
                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
            },
        },
        conductStaff: null,
        transaction: {
            id: 13,
            transactionType: 'Thanh toán',
            amount: 275000,
            paymentTime: '2023-11-13T15:39:27.203279',
            referenceId: 'FDZ0Z918YR',
            paymentMethod: 'Momo',
        },
        tickets: [
            {
                id: 91,
                seat: 'A8',
                state: 'Đã hủy',
                checkedIn: false,
                histories: [
                    {
                        id: 5,
                        action: 'Đổi',
                        timestamp: '2023-11-15T21:39:20.231654',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 8,
                            action: 'Đổi',
                            timeRequired: 24,
                            numberRequired: 30,
                            minNumberRequired: 1,
                            refundRate: 0,
                            description:
                                'Khách hàng được hỗ trợ đổi vé một lần duy nhất nếu yêu cầu đổi vé trước ít nhất 24 tiếng trước giờ khởi hành',
                        },
                        transaction: null,
                    },
                    {
                        id: 13,
                        action: 'Đổi',
                        timestamp: '2023-11-16T21:53:35.716253',
                        user: {
                            id: 6,
                            name: 'Lê Thị Kim Lệ Kim',
                            email: '20110248@student.hcmute.edu.vn',
                            tel: '09090909091',
                            gender: 'false',
                            account: {
                                id: 8,
                                username: '09090909091',
                                roleName: 'CUSTOMER',
                                active: true,
                            },
                            customer: {
                                customerId: 5,
                                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
                            },
                        },
                        policy: {
                            id: 2,
                            action: 'Hủy',
                            timeRequired: 4,
                            numberRequired: 3,
                            minNumberRequired: 1,
                            refundRate: 0.9,
                            description:
                                'Khách hàng hủy từ 1-3 vé trước ít nhất 4 tiếng trước giờ khởi hành sẽ được hoàn 90% tiền vé đối với vé thường',
                        },
                        transaction: {
                            id: 15,
                            transactionType: 'Hoàn tiền',
                            amount: 247500,
                            paymentTime: '2023-11-16T21:53:35.712059',
                            referenceId: 'Z4UIJS0MZU',
                            paymentMethod: 'Momo',
                        },
                    },
                ],
                schedule: {
                    id: 20,
                    departDate: '2023-12-12',
                    departTime: '07:00:00',
                    ticketPrice: 275000,
                    finishTime: '00:00:00',
                    availability: 9,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
        ],
        trip: {
            id: 4,
            turn: false,
            startStation: {
                id: 2,
                name: 'BX Miền Tây',
                address: '395 Kinh Dương Vương , P.An Lạc , Q.Bình Tân , TP.HCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.7406234,
                longitude: 106.6181474,
            },
            endStation: {
                id: 6,
                name: 'BX Bến Tre',
                address: 'QL60, Hữu Định, Tp. Bến Tre, Bến Tre',
                location: {
                    id: 3,
                    name: 'Bến Tre',
                },
                latitude: 10.2667393,
                longitude: 106.3590945,
            },
            route: {
                id: 2,
                distance: 75,
                departure: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                destination: {
                    id: 3,
                    name: 'Bến Tre',
                },
                price: 130000,
                schedule: 'QL1A -> Tân An -> Mỹ Tho -> Bến Tre -> Trà Vinh',
                parents: 1,
                hours: 2,
                busType: {
                    id: 2,
                    name: 'bumk_bus',
                    capacity: 33,
                    fee: 20000,
                    description: 'Xe giường nằm 43 chỗ',
                    seatMap: {
                        id: 2,
                        rowNo: 7,
                        colNo: 5,
                        floorNo: 2,
                        seats: [
                            {
                                id: 29,
                                name: 'A01',
                                row: 0,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 30,
                                name: 'A02',
                                row: 0,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 31,
                                name: 'A03',
                                row: 0,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 32,
                                name: 'A04',
                                row: 1,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 33,
                                name: 'A05',
                                row: 1,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 34,
                                name: 'A06',
                                row: 1,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 35,
                                name: 'A07',
                                row: 2,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 36,
                                name: 'A08',
                                row: 2,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 37,
                                name: 'A09',
                                row: 2,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 38,
                                name: 'A10',
                                row: 3,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 39,
                                name: 'A11',
                                row: 3,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 40,
                                name: 'A12',
                                row: 3,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 41,
                                name: 'A13',
                                row: 4,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 42,
                                name: 'A14',
                                row: 4,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 43,
                                name: 'A15',
                                row: 4,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 44,
                                name: 'A16',
                                row: 5,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 45,
                                name: 'A17',
                                row: 5,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 46,
                                name: 'A18',
                                row: 6,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 47,
                                name: 'A19',
                                row: 6,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 48,
                                name: 'A20',
                                row: 6,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 49,
                                name: 'A21',
                                row: 6,
                                col: 3,
                                floor: 1,
                            },
                            {
                                id: 50,
                                name: 'A22',
                                row: 6,
                                col: 4,
                                floor: 1,
                            },
                            {
                                id: 51,
                                name: 'B01',
                                row: 0,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 52,
                                name: 'B02',
                                row: 0,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 53,
                                name: 'B03',
                                row: 0,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 54,
                                name: 'B04',
                                row: 1,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 55,
                                name: 'B05',
                                row: 1,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 56,
                                name: 'B06',
                                row: 1,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 57,
                                name: 'B07',
                                row: 2,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 58,
                                name: 'B08',
                                row: 2,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 59,
                                name: 'B09',
                                row: 2,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 60,
                                name: 'B10',
                                row: 3,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 61,
                                name: 'B11',
                                row: 3,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 62,
                                name: 'B12',
                                row: 3,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 63,
                                name: 'B13',
                                row: 4,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 64,
                                name: 'B14',
                                row: 4,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 65,
                                name: 'B15',
                                row: 4,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 66,
                                name: 'B17',
                                row: 5,
                                col: 4,
                                floor: 2,
                            },
                            {
                                id: 67,
                                name: 'B18',
                                row: 6,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 68,
                                name: 'B19',
                                row: 6,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 69,
                                name: 'B20',
                                row: 6,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 70,
                                name: 'B21',
                                row: 6,
                                col: 3,
                                floor: 2,
                            },
                            {
                                id: 71,
                                name: 'B22',
                                row: 6,
                                col: 4,
                                floor: 2,
                            },
                        ],
                    },
                },
            },
        },
        ticketing: false,
    },
    {
        code: '85EM4Z',
        pickStation: {
            id: 66,
            arrivalTime: 0,
            stationType: 'pick',
            station: {
                id: 11,
                name: 'VP An Nhơn',
                address: '02 Nguyễn Văn Linh, P.Bình Định, Tx.An Nhơn, Tỉnh Bình Định',
                location: {
                    id: 7,
                    name: 'Bình Định',
                },
                latitude: 13.8860211,
                longitude: 109.1077389,
            },
        },
        dropStation: {
            id: 63,
            arrivalTime: 0,
            stationType: 'drop',
            station: {
                id: 1,
                name: 'BX Miền Đông Mới',
                address: '39448 Xa Lộ Hà Nội, Phường Long Bình, TP Thủ Đức, TPHCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.8782831,
                longitude: 106.8134822,
            },
        },
        bookingDate: '2023-11-16T21:55:27.77823',
        ticketNumber: 3,
        name: 'Lê Thị Kim Lệ',
        email: '20110248@student.hcmute.edu.vn',
        tel: '09090909091',
        status: 'Thành công',
        bookingUser: {
            id: 6,
            name: 'Lê Thị Kim Lệ Kim',
            email: '20110248@student.hcmute.edu.vn',
            tel: '09090909091',
            gender: 'false',
            account: {
                id: 8,
                username: '09090909091',
                roleName: 'CUSTOMER',
                active: true,
            },
            customer: {
                customerId: 5,
                img: 'https://bookingupfile.s3.amazonaws.com/Image/1700382651565-anh-chipi-16.jpg',
            },
        },
        conductStaff: null,
        transaction: {
            id: 16,
            transactionType: 'Thanh toán',
            amount: 1050000,
            paymentTime: '2023-11-16T21:55:48.812575',
            referenceId: 'FHGEXZF2CM',
            paymentMethod: 'Momo',
        },
        tickets: [
            {
                id: 93,
                seat: 'B17',
                state: 'Đã thanh toán',
                checkedIn: false,
                histories: [],
                schedule: {
                    id: 97,
                    departDate: '2023-12-12',
                    departTime: '23:30:00',
                    ticketPrice: 350000,
                    finishTime: '00:00:00',
                    availability: 1,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
            {
                id: 94,
                seat: 'B16',
                state: 'Đã thanh toán',
                checkedIn: false,
                histories: [],
                schedule: {
                    id: 97,
                    departDate: '2023-12-12',
                    departTime: '23:30:00',
                    ticketPrice: 350000,
                    finishTime: '00:00:00',
                    availability: 1,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
            {
                id: 95,
                seat: 'B15',
                state: 'Đã thanh toán',
                checkedIn: false,
                histories: [],
                schedule: {
                    id: 97,
                    departDate: '2023-12-12',
                    departTime: '23:30:00',
                    ticketPrice: 350000,
                    finishTime: '00:00:00',
                    availability: 1,
                    note: 'Xe có lộ trình đi cao tốc',
                    bus: null,
                },
            },
        ],
        trip: {
            id: 18,
            turn: false,
            startStation: {
                id: 1,
                name: 'BX Miền Đông Mới',
                address: '39448 Xa Lộ Hà Nội, Phường Long Bình, TP Thủ Đức, TPHCM',
                location: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                latitude: 10.8782831,
                longitude: 106.8134822,
            },
            endStation: {
                id: 11,
                name: 'VP An Nhơn',
                address: '02 Nguyễn Văn Linh, P.Bình Định, Tx.An Nhơn, Tỉnh Bình Định',
                location: {
                    id: 7,
                    name: 'Bình Định',
                },
                latitude: 13.8860211,
                longitude: 109.1077389,
            },
            route: {
                id: 6,
                distance: 585,
                departure: {
                    id: 1,
                    name: 'TP. Hồ Chí Minh',
                },
                destination: {
                    id: 7,
                    name: 'Bình Định',
                },
                price: 350000,
                schedule:
                    'QL1A -> Đồng Nai -> Bình Thuận -> Ninh Thuận -> Cam Ranh -> Nha Trang -> Bình Định',
                parents: 7,
                hours: 14,
                busType: {
                    id: 3,
                    name: 'limousine',
                    capacity: 43,
                    fee: 30000,
                    description: 'Xe limousine 33 chỗ',
                    seatMap: {
                        id: 3,
                        rowNo: 6,
                        colNo: 3,
                        floorNo: 2,
                        seats: [
                            {
                                id: 72,
                                name: 'A01',
                                row: 0,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 73,
                                name: 'A02',
                                row: 0,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 74,
                                name: 'A03',
                                row: 1,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 75,
                                name: 'A04',
                                row: 1,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 76,
                                name: 'A05',
                                row: 1,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 77,
                                name: 'A06',
                                row: 2,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 78,
                                name: 'A07',
                                row: 2,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 79,
                                name: 'A08',
                                row: 2,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 80,
                                name: 'A09',
                                row: 3,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 81,
                                name: 'A10',
                                row: 3,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 82,
                                name: 'A11',
                                row: 3,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 83,
                                name: 'A12',
                                row: 4,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 84,
                                name: 'A13',
                                row: 4,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 85,
                                name: 'A14',
                                row: 4,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 86,
                                name: 'A15',
                                row: 5,
                                col: 0,
                                floor: 1,
                            },
                            {
                                id: 87,
                                name: 'A16',
                                row: 5,
                                col: 1,
                                floor: 1,
                            },
                            {
                                id: 88,
                                name: 'A17',
                                row: 5,
                                col: 2,
                                floor: 1,
                            },
                            {
                                id: 89,
                                name: 'B02',
                                row: 0,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 90,
                                name: 'B03',
                                row: 1,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 91,
                                name: 'B04',
                                row: 1,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 92,
                                name: 'B05',
                                row: 1,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 93,
                                name: 'B06',
                                row: 2,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 94,
                                name: 'B07',
                                row: 2,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 95,
                                name: 'B08',
                                row: 2,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 96,
                                name: 'B09',
                                row: 3,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 97,
                                name: 'B10',
                                row: 3,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 98,
                                name: 'B11',
                                row: 3,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 99,
                                name: 'B12',
                                row: 4,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 100,
                                name: 'B13',
                                row: 4,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 101,
                                name: 'B14',
                                row: 4,
                                col: 2,
                                floor: 2,
                            },
                            {
                                id: 102,
                                name: 'B15',
                                row: 5,
                                col: 0,
                                floor: 2,
                            },
                            {
                                id: 103,
                                name: 'B16',
                                row: 5,
                                col: 1,
                                floor: 2,
                            },
                            {
                                id: 104,
                                name: 'B17',
                                row: 5,
                                col: 2,
                                floor: 2,
                            },
                        ],
                    },
                },
            },
        },
        ticketing: false,
    },
]
