export const listTicket = [
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A01',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Chờ thanh toán',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A05',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A09',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'B05',
        state: 'Chờ thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A10',
        state: 'Đã hủy',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A11',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A08',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'B03',
        state: 'Chờ thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A02',
        state: 'Đã thanh toán',
        cancelRequestId: null,
    },
    {
        id: 1,
        bill_id: 123,
        checkedIn: false,
        ticketPrice: 250,
        isTicketing: true,
        booking: {
            code: 'ABC',
            bookingUser: {
                id: 1,
                gender: false,
                tel: '07890567890',
                email: '123@gmail.com',
                name: 'Hưng',
            },
            conductStaff: {
                user: {
                    id: 3,
                    gender: false,
                    tel: '07890567890',
                    email: '123@gmail.com',
                    name: 'Hiền',
                },
            },
            pickStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Tây',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            dropStation: {
                id: 3,
                tripId: 4,
                station: {
                    id: 5,
                    name: 'BX Miền Đông',
                    address: 'Ho Chi Minh',
                },
                stationType: 'drop',
                arrival_time: '00:00', // Chưa có xử lý cái này
            },
            ticketNumber: 3,
            transactionId: 113,
            tripId: 1,
            bookingDate: '2023-10-20',
            email: '123@gmail.com',
            status: 'Thành công',
            tel: '0908907890',
            name: 'Nam',
        },
        seat: 'A12',
        state: 'Chờ thanh toán',
        cancelRequestId: null,
    },
]
